spring.application.name=fashionapp
spring.datasource.url=jdbc:postgresql://localhost:5432/fashiondb
spring.datasource.username=postgres
spring.datasource.password=Emmanuel

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true